--
-- PostgreSQL database dump
--

\restrict N8sCEshmAU25LwghTdSVbnrRRA8fHf0kTeSYRSEvkwy5vaxerZCDBhfby7hDb3i

-- Dumped from database version 17.9 (Ubuntu 17.9-1.pgdg22.04+1)
-- Dumped by pg_dump version 17.9 (Ubuntu 17.9-1.pgdg22.04+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: batch_detail; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.batch_detail (
    batch_detail_id character varying(255) NOT NULL,
    avg_rate numeric(19,4),
    created_at timestamp(6) without time zone NOT NULL,
    delete_at timestamp(6) without time zone,
    detail_content text,
    num_rate integer,
    price numeric(19,4),
    product_general_id bigint,
    quantity integer,
    updated_at timestamp(6) without time zone
);


--
-- Name: buyer; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.buyer (
    buyer_id character varying(255) NOT NULL,
    active_yn character varying(255),
    alias_nm character varying(255),
    avatar character varying(255),
    back_ground character varying(255),
    created_at timestamp(6) without time zone NOT NULL,
    delete_at timestamp(6) without time zone,
    detail jsonb,
    email character varying(255),
    list_address jsonb,
    name character varying(255),
    phone character varying(255),
    sex character varying(255),
    updated_at timestamp(6) without time zone
);


--
-- Name: category; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.category (
    category_id bigint NOT NULL,
    belong_to_category bigint,
    category_name character varying(255) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    description text,
    display_order integer,
    icon_url character varying(255),
    is_sub_category character varying(255),
    updated_at timestamp(6) without time zone
);


--
-- Name: category_category_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.category ALTER COLUMN category_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.category_category_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: feed_back; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.feed_back (
    feedback_id bigint NOT NULL,
    buyer_id character varying(255),
    content text,
    created_at timestamp(6) without time zone NOT NULL,
    delete_at timestamp(6) without time zone,
    detail jsonb,
    img text,
    product_detail_id bigint,
    rating numeric(3,2),
    reply_id bigint,
    updated_at timestamp(6) without time zone
);


--
-- Name: feed_back_feedback_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.feed_back ALTER COLUMN feedback_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.feed_back_feedback_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: order_item; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.order_item (
    order_item_id bigint NOT NULL,
    batch_id character varying(255),
    created_at timestamp(6) without time zone,
    order_id bigint,
    original_price numeric(38,2),
    product_detail_id bigint,
    product_general_id bigint,
    quantity bigint,
    sale_price numeric(38,2),
    temp_yn character varying(255),
    updated_at timestamp(6) without time zone
);


--
-- Name: order_item_order_item_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.order_item ALTER COLUMN order_item_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.order_item_order_item_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: orders; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.orders (
    order_id bigint NOT NULL,
    buyer_id character varying(255),
    coupon_id character varying(255),
    created_at timestamp(6) without time zone,
    deleted_at timestamp(6) without time zone,
    note character varying(255),
    status character varying(255),
    total_price bigint,
    type smallint,
    updated_at timestamp(6) without time zone,
    CONSTRAINT orders_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'PAID'::character varying, 'CONFIRMED'::character varying, 'PACKAGED'::character varying, 'SHIPPED'::character varying, 'COMPLETED'::character varying, 'CANCELLED'::character varying])::text[]))),
    CONSTRAINT orders_type_check CHECK (((type >= 0) AND (type <= 2)))
);


--
-- Name: orders_order_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.orders ALTER COLUMN order_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.orders_order_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: product_detail; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.product_detail (
    product_detail_id bigint NOT NULL,
    batch_id character varying(255) NOT NULL,
    buy_yn character varying(255),
    created_at timestamp(6) without time zone NOT NULL,
    deleted_at timestamp(6) without time zone,
    detail jsonb,
    img text,
    product_general_id bigint NOT NULL,
    rating numeric(10,2),
    status character varying(255),
    updated_at timestamp(6) without time zone
);


--
-- Name: product_detail_product_detail_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.product_detail ALTER COLUMN product_detail_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.product_detail_product_detail_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: product_general; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.product_general (
    product_general_id bigint NOT NULL,
    category_id bigint,
    created_at timestamp(6) without time zone NOT NULL,
    delete_at timestamp(6) without time zone,
    description text,
    img text,
    name character varying(255) NOT NULL,
    provider_id character varying(255),
    status character varying(255),
    tags text[],
    updated_at timestamp(6) without time zone
);


--
-- Name: product_general_product_general_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.product_general ALTER COLUMN product_general_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.product_general_product_general_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sale_event; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sale_event (
    sale_event_id bigint NOT NULL,
    active_yn character varying(255),
    begin_date timestamp(6) without time zone,
    begin_time time(6) without time zone,
    created_at timestamp(6) without time zone,
    delete_at timestamp(6) without time zone,
    description character varying(255),
    detail jsonb,
    display_priority bigint,
    enabled_yn character varying(255),
    end_date timestamp(6) without time zone,
    end_time time(6) without time zone,
    img text,
    name character varying(255),
    updated_at timestamp(6) without time zone
);


--
-- Name: sale_event_sale_event_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.sale_event ALTER COLUMN sale_event_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sale_event_sale_event_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sale_product; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sale_product (
    sale_event_id bigint NOT NULL,
    batch_id character varying(255),
    created_at timestamp(6) without time zone,
    cur_qty bigint,
    delete_at timestamp(6) without time zone,
    dis_val numeric(10,2),
    max_buy bigint,
    max_qty bigint,
    updated_at timestamp(6) without time zone
);


--
-- Data for Name: batch_detail; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.batch_detail (batch_detail_id, avg_rate, created_at, delete_at, detail_content, num_rate, price, product_general_id, quantity, updated_at) FROM stdin;
\.


--
-- Data for Name: buyer; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.buyer (buyer_id, active_yn, alias_nm, avatar, back_ground, created_at, delete_at, detail, email, list_address, name, phone, sex, updated_at) FROM stdin;
\.


--
-- Data for Name: category; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.category (category_id, belong_to_category, category_name, created_at, description, display_order, icon_url, is_sub_category, updated_at) FROM stdin;
6	\N	Trứng & Sữa	2026-03-19 18:54:27.729983	Trứng gia cầm tươi và các sản phẩm từ sữa	5	https://example.com/eggs-dairy-icon.png	N	\N
7	\N	Trứng & Sữa	2026-03-19 18:56:14.382367	Trứng gia cầm tươi và các sản phẩm từ sữa	5	https://example.com/eggs-dairy-icon.png	N	\N
\.


--
-- Data for Name: feed_back; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.feed_back (feedback_id, buyer_id, content, created_at, delete_at, detail, img, product_detail_id, rating, reply_id, updated_at) FROM stdin;
\.


--
-- Data for Name: order_item; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.order_item (order_item_id, batch_id, created_at, order_id, original_price, product_detail_id, product_general_id, quantity, sale_price, temp_yn, updated_at) FROM stdin;
\.


--
-- Data for Name: orders; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.orders (order_id, buyer_id, coupon_id, created_at, deleted_at, note, status, total_price, type, updated_at) FROM stdin;
\.


--
-- Data for Name: product_detail; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.product_detail (product_detail_id, batch_id, buy_yn, created_at, deleted_at, detail, img, product_general_id, rating, status, updated_at) FROM stdin;
\.


--
-- Data for Name: product_general; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.product_general (product_general_id, category_id, created_at, delete_at, description, img, name, provider_id, status, tags, updated_at) FROM stdin;
1	1	2026-03-19 18:04:41.178767	\N	Cà chua Đà Lạt tươi ngon, giàu vitamin C, thích hợp cho món salad và nấu canh	https://example.com/ca-chua-dalat.jpg	Cà Chua Đà Lạt	\N	ACTIVE	{"rau củ","cà chua","đà lạt",vitamin}	\N
2	1	2026-03-19 18:05:08.975719	\N	Rau muống trồng theo phương pháp hữu cơ, an toàn không hóa chất, tươi mới mỗi ngày	https://example.com/rau-muong-organic.jpg	Rau Muống Organic	\N	ACTIVE	{"rau lá",organic,"an toàn","rau muống"}	\N
3	1	2026-03-19 18:05:16.014664	\N	Khoai tây Đà Lạt chất lượng cao, thịt vàng bở, thích hợp chiên, xào, nấu canh	https://example.com/khoai-tay-dalat.jpg	Khoai Tây Đà Lạt	\N	ACTIVE	{củ,"khoai tây","đà lạt","tinh bột"}	\N
4	1	2026-03-19 18:05:21.993926	\N	Bí đỏ hữu cơ giàu beta-carotene, thịt ngọt và bở, tốt cho sức khỏe	https://example.com/bi-do-huu-co.jpg	Bí Đỏ Hữu Cơ	\N	ACTIVE	{quả,"bí đỏ",organic,"dinh dưỡng"}	\N
5	1	2026-03-19 18:05:26.794157	\N	Cải thảo Đà Lạt tươi ngon, lá xanh mướt, giòn ngọt, thích hợp nấu lẩu và xào	https://example.com/cai-thao-dalat.jpg	Cải Thảo Đà Lạt	\N	ACTIVE	{"rau lá","cải thảo","đà lạt","tươi sống"}	\N
6	7	2026-03-19 18:56:25.70351	\N	Cải thảo Đà Lạt tươi ngon, lá xanh mướt, giòn ngọt, thích hợp nấu lẩu và xào	https://example.com/cai-thao-dalat.jpg	Cải Thảo Đà Lạt	\N	ACTIVE	{"rau lá","cải thảo","đà lạt","tươi sống"}	\N
\.


--
-- Data for Name: sale_event; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.sale_event (sale_event_id, active_yn, begin_date, begin_time, created_at, delete_at, description, detail, display_priority, enabled_yn, end_date, end_time, img, name, updated_at) FROM stdin;
\.


--
-- Data for Name: sale_product; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.sale_product (sale_event_id, batch_id, created_at, cur_qty, delete_at, dis_val, max_buy, max_qty, updated_at) FROM stdin;
\.


--
-- Name: category_category_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.category_category_id_seq', 7, true);


--
-- Name: feed_back_feedback_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.feed_back_feedback_id_seq', 1, false);


--
-- Name: order_item_order_item_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.order_item_order_item_id_seq', 1, false);


--
-- Name: orders_order_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.orders_order_id_seq', 1, false);


--
-- Name: product_detail_product_detail_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.product_detail_product_detail_id_seq', 1, false);


--
-- Name: product_general_product_general_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.product_general_product_general_id_seq', 6, true);


--
-- Name: sale_event_sale_event_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.sale_event_sale_event_id_seq', 1, false);


--
-- Name: batch_detail batch_detail_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.batch_detail
    ADD CONSTRAINT batch_detail_pkey PRIMARY KEY (batch_detail_id);


--
-- Name: buyer buyer_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.buyer
    ADD CONSTRAINT buyer_pkey PRIMARY KEY (buyer_id);


--
-- Name: category category_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.category
    ADD CONSTRAINT category_pkey PRIMARY KEY (category_id);


--
-- Name: feed_back feed_back_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.feed_back
    ADD CONSTRAINT feed_back_pkey PRIMARY KEY (feedback_id);


--
-- Name: order_item order_item_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.order_item
    ADD CONSTRAINT order_item_pkey PRIMARY KEY (order_item_id);


--
-- Name: orders orders_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT orders_pkey PRIMARY KEY (order_id);


--
-- Name: product_detail product_detail_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_detail
    ADD CONSTRAINT product_detail_pkey PRIMARY KEY (product_detail_id);


--
-- Name: product_general product_general_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_general
    ADD CONSTRAINT product_general_pkey PRIMARY KEY (product_general_id);


--
-- Name: sale_event sale_event_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sale_event
    ADD CONSTRAINT sale_event_pkey PRIMARY KEY (sale_event_id);


--
-- Name: sale_product sale_product_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sale_product
    ADD CONSTRAINT sale_product_pkey PRIMARY KEY (sale_event_id);


--
-- Name: batch_detail batch_detail_product_general_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.batch_detail
    ADD CONSTRAINT batch_detail_product_general_id_fkey FOREIGN KEY (product_general_id) REFERENCES public.product_general(product_general_id) NOT VALID;


--
-- Name: category category_belong_to_category_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.category
    ADD CONSTRAINT category_belong_to_category_fkey FOREIGN KEY (belong_to_category) REFERENCES public.category(category_id) NOT VALID;


--
-- Name: feed_back feed_back_product_detail_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.feed_back
    ADD CONSTRAINT feed_back_product_detail_id_fkey FOREIGN KEY (product_detail_id) REFERENCES public.product_detail(product_detail_id) NOT VALID;


--
-- Name: order_item order_item_batch_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.order_item
    ADD CONSTRAINT order_item_batch_id_fkey FOREIGN KEY (batch_id) REFERENCES public.batch_detail(batch_detail_id) NOT VALID;


--
-- Name: order_item order_item_order_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.order_item
    ADD CONSTRAINT order_item_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(order_id) NOT VALID;


--
-- Name: order_item order_item_product_detail_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.order_item
    ADD CONSTRAINT order_item_product_detail_id_fkey FOREIGN KEY (product_detail_id) REFERENCES public.product_detail(product_detail_id) NOT VALID;


--
-- Name: order_item order_item_product_general_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.order_item
    ADD CONSTRAINT order_item_product_general_id_fkey FOREIGN KEY (product_general_id) REFERENCES public.product_general(product_general_id) NOT VALID;


--
-- Name: orders orders_buyer_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT orders_buyer_id_fkey FOREIGN KEY (buyer_id) REFERENCES public.buyer(buyer_id) NOT VALID;


--
-- Name: product_detail product_detail_batch_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_detail
    ADD CONSTRAINT product_detail_batch_id_fkey FOREIGN KEY (batch_id) REFERENCES public.batch_detail(batch_detail_id) NOT VALID;


--
-- Name: product_detail product_detail_product_general_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_detail
    ADD CONSTRAINT product_detail_product_general_id_fkey FOREIGN KEY (product_general_id) REFERENCES public.product_general(product_general_id) NOT VALID;


--
-- Name: product_general product_general_category_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_general
    ADD CONSTRAINT product_general_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.category(category_id) NOT VALID;


--
-- Name: sale_product sale_product_batch_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sale_product
    ADD CONSTRAINT sale_product_batch_id_fkey FOREIGN KEY (batch_id) REFERENCES public.batch_detail(batch_detail_id) NOT VALID;


--
-- PostgreSQL database dump complete
--

\unrestrict N8sCEshmAU25LwghTdSVbnrRRA8fHf0kTeSYRSEvkwy5vaxerZCDBhfby7hDb3i

