--
-- PostgreSQL database dump
--

\restrict YkwwaYWxR1LlfhC96NXNP0D1fYjMsWFaBUHwuTuqL3IQg3b7YKI8fskMSiUMCXS

-- Dumped from database version 17.9 (Debian 17.9-1.pgdg13+1)
-- Dumped by pg_dump version 17.9 (Ubuntu 17.9-1.pgdg22.04+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: address; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.address (
    address_id bigint NOT NULL,
    buyer_id character varying(255),
    commune character varying(255),
    detail character varying(255),
    district character varying(255),
    is_default boolean,
    province character varying(255),
    receiver_name character varying(255),
    receiver_p_num character varying(255)
);


--
-- Name: address_address_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.address ALTER COLUMN address_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.address_address_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: batch_detail; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.batch_detail (
    batch_detail_id character varying(255) NOT NULL,
    avg_rate numeric(19,4),
    created_at timestamp(6) without time zone NOT NULL,
    delete_at timestamp(6) without time zone,
    detail_content text,
    num_rate integer,
    price numeric(19,4),
    product_general_id bigint,
    quantity integer,
    updated_at timestamp(6) without time zone
);


--
-- Name: buyer; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.buyer (
    buyer_id character varying(255) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    email character varying(255),
    f_name character varying(255),
    l_name character varying(255),
    updated_at timestamp(6) without time zone
);


--
-- Name: cart; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.cart (
    card_id bigint NOT NULL,
    buyer_id character varying(255),
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone
);


--
-- Name: cart_card_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.cart ALTER COLUMN card_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cart_card_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cart_item; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.cart_item (
    cart_item_id bigint NOT NULL,
    cart_id bigint,
    created_at timestamp(6) without time zone,
    is_selected boolean,
    quantity bigint,
    updated_at timestamp(6) without time zone,
    batch_detail_id character varying(255)
);


--
-- Name: cart_item_cart_item_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.cart_item ALTER COLUMN cart_item_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cart_item_cart_item_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: category; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.category (
    category_id bigint NOT NULL,
    belong_to_category bigint,
    category_name character varying(255) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    description text,
    display_order integer,
    icon_url character varying(255),
    is_sub_category character varying(255),
    updated_at timestamp(6) without time zone
);


--
-- Name: category_category_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.category ALTER COLUMN category_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.category_category_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: feed_back; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.feed_back (
    feedback_id bigint NOT NULL,
    buyer_id character varying(255),
    content text,
    created_at timestamp(6) without time zone NOT NULL,
    delete_at timestamp(6) without time zone,
    detail jsonb,
    img text,
    product_detail_id bigint,
    rating numeric(3,2),
    reply_id bigint,
    updated_at timestamp(6) without time zone
);


--
-- Name: feed_back_feedback_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.feed_back ALTER COLUMN feedback_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.feed_back_feedback_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: order_item; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.order_item (
    order_item_id bigint NOT NULL,
    batch_detail_id character varying(255),
    created_at timestamp(6) without time zone,
    order_id bigint,
    original_price numeric(38,2),
    quantity bigint,
    unit_price_at_purchase numeric(38,2),
    updated_at timestamp(6) without time zone
);


--
-- Name: order_item_order_item_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.order_item ALTER COLUMN order_item_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.order_item_order_item_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: orders; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.orders (
    order_id bigint NOT NULL,
    buyer_id character varying(255),
    coupon_id character varying(255),
    created_at timestamp(6) without time zone,
    note character varying(255),
    status character varying(255),
    total_price bigint,
    type smallint,
    updated_at timestamp(6) without time zone,
    address_id character varying(255),
    CONSTRAINT orders_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'PAID'::character varying, 'CONFIRMED'::character varying, 'PACKAGED'::character varying, 'SHIPPED'::character varying, 'COMPLETED'::character varying, 'CANCELLED'::character varying])::text[]))),
    CONSTRAINT orders_type_check CHECK (((type >= 0) AND (type <= 2)))
);


--
-- Name: orders_order_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.orders ALTER COLUMN order_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.orders_order_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: product_detail; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.product_detail (
    product_detail_id bigint NOT NULL,
    batch_id character varying(255) NOT NULL,
    buy_yn character varying(255),
    created_at timestamp(6) without time zone NOT NULL,
    deleted_at timestamp(6) without time zone,
    detail jsonb,
    img text,
    product_general_id bigint NOT NULL,
    rating numeric(10,2),
    status character varying(255),
    updated_at timestamp(6) without time zone
);


--
-- Name: product_detail_product_detail_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.product_detail ALTER COLUMN product_detail_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.product_detail_product_detail_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: product_general; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.product_general (
    product_general_id bigint NOT NULL,
    category_id bigint,
    created_at timestamp(6) without time zone NOT NULL,
    delete_at timestamp(6) without time zone,
    description text,
    img text,
    name character varying(255) NOT NULL,
    provider_id character varying(255),
    status character varying(255),
    tags text[],
    updated_at timestamp(6) without time zone
);


--
-- Name: product_general_product_general_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.product_general ALTER COLUMN product_general_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.product_general_product_general_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sale_event; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sale_event (
    sale_event_id bigint NOT NULL,
    active_yn character varying(255),
    begin_date timestamp(6) without time zone,
    begin_time time(6) without time zone,
    created_at timestamp(6) without time zone,
    delete_at timestamp(6) without time zone,
    description character varying(255),
    detail jsonb,
    display_priority bigint,
    enabled_yn character varying(255),
    end_date timestamp(6) without time zone,
    end_time time(6) without time zone,
    img text,
    name character varying(255),
    updated_at timestamp(6) without time zone
);


--
-- Name: sale_event_sale_event_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.sale_event ALTER COLUMN sale_event_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sale_event_sale_event_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sale_product; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sale_product (
    sale_event_id bigint NOT NULL,
    batch_id character varying(255),
    created_at timestamp(6) without time zone,
    cur_qty bigint,
    delete_at timestamp(6) without time zone,
    dis_val numeric(10,2),
    max_buy bigint,
    max_qty bigint,
    updated_at timestamp(6) without time zone
);


--
-- Data for Name: address; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.address (address_id, buyer_id, commune, detail, district, is_default, province, receiver_name, receiver_p_num) FROM stdin;
\.


--
-- Data for Name: batch_detail; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.batch_detail (batch_detail_id, avg_rate, created_at, delete_at, detail_content, num_rate, price, product_general_id, quantity, updated_at) FROM stdin;
\.


--
-- Data for Name: buyer; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.buyer (buyer_id, created_at, email, f_name, l_name, updated_at) FROM stdin;
\.


--
-- Data for Name: cart; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.cart (card_id, buyer_id, created_at, updated_at) FROM stdin;
\.


--
-- Data for Name: cart_item; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.cart_item (cart_item_id, cart_id, created_at, is_selected, quantity, updated_at, batch_detail_id) FROM stdin;
\.


--
-- Data for Name: category; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.category (category_id, belong_to_category, category_name, created_at, description, display_order, icon_url, is_sub_category, updated_at) FROM stdin;
\.


--
-- Data for Name: feed_back; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.feed_back (feedback_id, buyer_id, content, created_at, delete_at, detail, img, product_detail_id, rating, reply_id, updated_at) FROM stdin;
\.


--
-- Data for Name: order_item; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.order_item (order_item_id, batch_detail_id, created_at, order_id, original_price, quantity, unit_price_at_purchase, updated_at) FROM stdin;
\.


--
-- Data for Name: orders; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.orders (order_id, buyer_id, coupon_id, created_at, note, status, total_price, type, updated_at, address_id) FROM stdin;
\.


--
-- Data for Name: product_detail; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.product_detail (product_detail_id, batch_id, buy_yn, created_at, deleted_at, detail, img, product_general_id, rating, status, updated_at) FROM stdin;
\.


--
-- Data for Name: product_general; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.product_general (product_general_id, category_id, created_at, delete_at, description, img, name, provider_id, status, tags, updated_at) FROM stdin;
\.


--
-- Data for Name: sale_event; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.sale_event (sale_event_id, active_yn, begin_date, begin_time, created_at, delete_at, description, detail, display_priority, enabled_yn, end_date, end_time, img, name, updated_at) FROM stdin;
\.


--
-- Data for Name: sale_product; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.sale_product (sale_event_id, batch_id, created_at, cur_qty, delete_at, dis_val, max_buy, max_qty, updated_at) FROM stdin;
\.


--
-- Name: address_address_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.address_address_id_seq', 1, false);


--
-- Name: cart_card_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.cart_card_id_seq', 1, false);


--
-- Name: cart_item_cart_item_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.cart_item_cart_item_id_seq', 1, false);


--
-- Name: category_category_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.category_category_id_seq', 1, false);


--
-- Name: feed_back_feedback_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.feed_back_feedback_id_seq', 1, false);


--
-- Name: order_item_order_item_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.order_item_order_item_id_seq', 1, false);


--
-- Name: orders_order_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.orders_order_id_seq', 1, false);


--
-- Name: product_detail_product_detail_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.product_detail_product_detail_id_seq', 1, false);


--
-- Name: product_general_product_general_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.product_general_product_general_id_seq', 1, false);


--
-- Name: sale_event_sale_event_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.sale_event_sale_event_id_seq', 1, false);


--
-- Name: address address_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.address
    ADD CONSTRAINT address_pkey PRIMARY KEY (address_id);


--
-- Name: batch_detail batch_detail_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.batch_detail
    ADD CONSTRAINT batch_detail_pkey PRIMARY KEY (batch_detail_id);


--
-- Name: buyer buyer_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.buyer
    ADD CONSTRAINT buyer_pkey PRIMARY KEY (buyer_id);


--
-- Name: cart_item cart_item_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cart_item
    ADD CONSTRAINT cart_item_pkey PRIMARY KEY (cart_item_id);


--
-- Name: cart cart_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cart
    ADD CONSTRAINT cart_pkey PRIMARY KEY (card_id);


--
-- Name: category category_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.category
    ADD CONSTRAINT category_pkey PRIMARY KEY (category_id);


--
-- Name: feed_back feed_back_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.feed_back
    ADD CONSTRAINT feed_back_pkey PRIMARY KEY (feedback_id);


--
-- Name: order_item order_item_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.order_item
    ADD CONSTRAINT order_item_pkey PRIMARY KEY (order_item_id);


--
-- Name: orders orders_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT orders_pkey PRIMARY KEY (order_id);


--
-- Name: product_detail product_detail_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_detail
    ADD CONSTRAINT product_detail_pkey PRIMARY KEY (product_detail_id);


--
-- Name: product_general product_general_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_general
    ADD CONSTRAINT product_general_pkey PRIMARY KEY (product_general_id);


--
-- Name: sale_event sale_event_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sale_event
    ADD CONSTRAINT sale_event_pkey PRIMARY KEY (sale_event_id);


--
-- Name: sale_product sale_product_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sale_product
    ADD CONSTRAINT sale_product_pkey PRIMARY KEY (sale_event_id);


--
-- PostgreSQL database dump complete
--

\unrestrict YkwwaYWxR1LlfhC96NXNP0D1fYjMsWFaBUHwuTuqL3IQg3b7YKI8fskMSiUMCXS

