spring:
  application:
    name: ecommerce_service

  config:
    import: optional:file:.env[.properties]

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/ecommerce_db?stringtype=unspecified
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

#decorator:
#  datasource:
#    p6spy:
#      enable-logging: true
#      multiline: true
#      logging: slf4j
#      tracing:
#        include-parameter-values: true

server:
  port: 9300

cloudflare:
  r2:
    account-id: ${R2_ACCOUNT_ID}
    endpoint: https://${R2_ACCOUNT_ID}.r2.cloudflarestorage.com
    access-key: ${R2_ACCESS_KEY}
    secret-key: ${R2_SECRET_KEY}
    region: auto

app:
  kafka-url:
    ${KAFKA_HOST}:${KAFKA_PORT}
  user-avater-bucket:
    back-office-user-avts
  product-general-img-bucket:
    product-general-img

google:
  sheets:
    credentials-path:
      google-credentials.json
    spreadsheet-id:
      1OgOhMyB660z8ITyLA8QZt39IWpz24qfT5GjjlcjT1m0

goong:
  api-key:
    ${GOONG_API_KEY}

# Polling interval (milliseconds) - 10 giây
payment:
  polling:
    interval: 10000

sepay:
  account: SEPTAK21191
  bank: OCB

services:
  identity:
    url: http://${IDENTITY_HOST:localhost}:${IDENTITY_PORT:9000}
  back-office:
    url: http://${BACK_OFFICE_HOST:localhost}:${BACK_OFFICE_PORT:9100}
  product-storage:
    url: http://${PRODUCT_STORAGE_HOST:localhost}:${PRODUCT_STORAGE_PORT:9200}