services:
  postgres:
    image: postgres:17
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: ecommerce_db
    ports:
      - "5433:5432"
    networks:
      - backend
    # healthcheck:
    #   test: ["CMD-SHELL", "pg_isready -U admin -d ecommerce_db"]
    #   interval: 5s
    #   timeout: 5s
    #   retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ecommerce-app
    restart: always
    depends_on:
      - postgres
      # postgres:
      #   condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/ecommerce_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin123
      SPRING_JPA_HIBERNATE_DDL_AUTO: create
      SERVER_PORT: 8080
    ports:
      - "8080:8080"
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend:
